name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: "Tests (${{ matrix.os }})"
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        env:
          cluster.routing.allocation.disk.threshold_enabled: false
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200
    strategy:
      matrix:
        go: ['1.18beta1']
    steps:
    - uses: actions/checkout@v2
      with: { fetch-depth: 1 }
    # - uses: actions/setup-go@v2
    #   with: { go-version: "${{ matrix.go }}" }
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: "${{ matrix.go }}"
    - uses: arduino/setup-protoc@v1
    - run: go version
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: make ES_HOST=localhost seed-testenv
    - run: make dependencies
    - run: make cover
    - uses: codecov/codecov-action@v2
      with:
        file: cover.out
